package automato;

public enum TokenLMS {
	//A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
	CHAR, DIGIT, ANYSPACE, ANY_SYMBOL_NONASTERISK, ANY_SYMBOL_NONQUOTE,
	ID, INTEIRO, LIT, PROGRAM, CONST, VAR, PROCEDURE, BEGIN, END, INTEGER,
	OF, CALL, IF, THEN, ELSE, WHILE, DO, REPEAT, UNTIL, READLN, WRITELN,
	OR, AND, NOT, FOR, TO, CASE;
}
